chore: remove behavior
camunda/zeebe-bpmn-moddle pull request #33
Opened 2022-08-23 07:26 UTC by philippfromme

BREAKING CHANGES

* behavior moved to https://github.com/camunda/camunda-bpmn-js-behaviors

---

Closes #29
Related to https://github.com/camunda/camunda-bpmn-js-behaviors/pull/5

2022-08-23 12:45 UTC, nikku requested changes
What's missing here:

* Update to README (pointing to camunda-bpmn-js-behaviors or something).

2022-08-24 07:16 UTC, philippfromme commented
> * Update to README (pointing to camunda-bpmn-js-behaviors or something).

Done: https://github.com/camunda/zeebe-bpmn-moddle/pull/33/commits/9f558bcf3c258f0f14e9728cfba418ccefbe56a4

2022-08-24 10:53 UTC, nikku commented on README.md
> +This extension should be used with [camunda-bpmn-js-behaviors](https://github.com/camunda/camunda-bpmn-js-behaviors) to ensure Camunda properties are created, updated and deleted as expected.
Could deep link camunda cloud extension section here.

2022-08-24 12:04 UTC, philippfromme commented on README.md
> +This extension should be used with [camunda-bpmn-js-behaviors](https://github.com/camunda/camunda-bpmn-js-behaviors) to ensure Camunda properties are created, updated and deleted as expected.
Good suggestion. 👍🏻

2022-08-24 12:07 UTC, philippfromme commented on README.md
> +This extension should be used with [camunda-bpmn-js-behaviors](https://github.com/camunda/camunda-bpmn-js-behaviors) to ensure Camunda properties are created, updated and deleted as expected.
Done (cf. https://github.com/camunda/zeebe-bpmn-moddle/pull/33/commits/89849e90528316b0d6ac04ab4d54529ce5bbaf7a#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R44).

2022-08-24 12:31 UTC, nikku approved these changes

2022-08-24 13:03 UTC, merged